<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.11.0" />
    <PackageReference Include="Anthropic.Bedrock" Version="0.1.2" />
    <PackageReference Include="Microsoft.Agents.Builder" Version="1.4.83" />
    <PackageReference Include="Microsoft.Agents.Core" Version="1.4.83" />
    <PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" Version="1.4.83" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
  </ItemGroup>

</Project>
