version: "3.4"
services:
  app7:
    build:
      context: App7
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__db=Server=db;Port=3306;Uid=root;Pwd=P@ssw0rd;Database=sample
    ports:
      - "8070:8080"
    depends_on:
      - db
  app8:
    build:
      context: App8
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__db=Server=db;Port=3306;Uid=root;Pwd=P@ssw0rd;Database=sample
    ports:
      - "8080:8080"
    depends_on:
      - db
  app8aot:
    build:
      context: App8Aot
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__db=Server=db;Port=3306;Uid=root;Pwd=P@ssw0rd;Database=sample
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
